### PR TITLE
Client metrics

### PR DESCRIPTION
**Pull request by OleMchls**
Add metrics for sidekiq client. I also want to track when a job is enqueued.

This one heavily depends on #5 so would be good to merge #5 first.

cheers :balloon:

### CODE REVIEW

**Comment by thibaudgg** [comment]
Is it Sidekiq 3.0 ready? https://github.com/mperham/sidekiq/blob/master/3.0-Upgrade.md

**Comment by OleMchls** [comment]
That's a good questions. I guess it's not. Because there is a new parameter (`redis_pool`) added and therefor I have to rework that one.

**Comment by OleMchls** [comment]
Now it should be ready for the sidekiq 3 upgrade

**Comment by thibaudgg** [comment]
:+1:

**Comment by OleMchls** [comment]
There were a few flaws left in the library, should be fixed now, deploying to production at the moment :shipit:

**Comment by OleMchls** [comment]
Alright, now it's ready! We already use it in production, even with sidekiq 3.

:steam_locomotive::shipit::train:.:train:.:train:.:train:

**Comment by OleMchls** [comment]
@scootklein what do you think?

**Comment by josephruscio** [comment]
@scootklein let us know if there's any way we can help with this.

**Comment by thibaudgg** [comment]
I get some `uninitialized constant Sidekiq::Stats` errors with that PR. I think that `require 'sidekiq/api'` is missing somewhere.

**Comment by OleMchls** [comment]
Could you provide steps to reproduce, the tests are running fine at my machine and we are also running it in production since a few weeks without any issues.

**Comment by thibaudgg** [comment]
Are you using sidekiq/web on the same app in production? 
Because `Sidekiq::Stats` is used [there on librato-sidekiq](https://github.com/StatusPage/librato-sidekiq/blob/master/lib/librato-sidekiq/middleware.rb#L66) but it's only required from the [sidekiq/web file](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L6).

**Comment by OleMchls** [comment]
Yes, we are also using the web part in production, and I just rechecked and it works like a charm. We are using sidekiq 3, what version are you using?

**Comment by scootklein** [comment]
Had this issue with our scout plugin just yesterday, we did a preemptive include so that it was version-agnostic and backward compatible.

`include 'sidekiq/api' rescue nil`

Think adding this will suffice?

**Comment by thibaudgg** [comment]
I added `gem 'sidekiq', require: ['sidekiq', 'sidekiq/api']` to my Gemfile to fix it, but it should be something require by librato-sidekiq directly.

**Pull request merged**
