### PR TITLE
Added the option to flush immediately

### PR DESCRIPTION
**Pull request by kemper**
We tried using this gem, but would not get any updates to Librato for sidekiq related metrics. We played around with it for a while, and the only thing we found that helped was manually forcing a flush at the end of the middleware after the librato calls. I see that librato has a flush interval, and I wasn't able to select a value for that that resulted in sidekiq sending the metrics to librato. I wouldn't want that number to be low anyway, since I want to use the librato-rails instrumentation throughout the app without slowing things down.

In case it helps at all, I'm using sidekiq 2.11.2, sidekiq-pro 1.0.0, ruby 1.9.3, rails 3.2.12, librato-metrics 1.1.1, and librato-rails 0.10.0.

I implemented this as an option so that it won't change the default behavior of the middleware. If you observe that this is a permanent bug caused by some newer version of something, you may want to default it to true.

### CODE REVIEW

**Comment by nextmat** [comment]
I think this is likely related to a change in startup behavior in librato-rails 0.10.0. Before if we didn't detect a forking server we started up the reporter thread immediately and now we wait until the first request (which of course never comes for something that isn't taking requests).

@kemper would you mind verifying if this is also an issue with v0.9.0 or if the behavior is new?

**Comment by kemper** [comment]
I tested it again, it does appear the behavior was introduced in version 0.10.0 of librato-rails. It just works with librato-rails 0.9.0 without forcing a flush.

**Comment by kemper** [comment]
actually, I think I mis-tested it. Let me try one more time.

**Comment by kemper** [comment]
I tested it again. It's working under librato-rails 0.9.0.

**Comment by scootklein** [comment]
great! thanks for the diligence

## 

sbk

**Comment by kemper** [comment]
Did you want me to create an issue in github? Also, should I rollback the
version to 0.9.0 for now and wait until you pursue an alternate fix?

**Comment by scootklein** [comment]
Go ahead and open up an issue with the corroborating data so i can get in touch with the Librato guys if necessary

## 

sbk

**Comment by nextmat** [comment]
I am the Librato guys. :-) Consider us notified. @scootklein I was actually going to ping you about this since I knew you were using sidekiq, @kemper sorry you ran into it first.

The fix in v0.10.0 and above is going to be to give librato-rails some config signal to start at startup, I've been toying with the idea of using `LIBRATO_AUTORUN=1` as a signal to start at startup.

However, I'm a little concerned that may be confusing as the primary behavior right now is to disable reporter startup or to start the reporter in console mode. Anyway, I've been debating that vs a different dedicated config option for clarity. Any strong opinions?

Our current config options: https://github.com/librato/librato-rails/wiki/Configuration#environment-variables

**Comment by nextmat** [comment]
Fixed in librato-rails v0.10.1, see https://github.com/librato/librato-rails/issues/78 for details.

**Comment by scootklein** [comment]
This is fixed in the most recent version of librato-sidekiq, closing.

**Pull request closed without merging**
